# shellcheck shell=bash
# shellcheck disable=SC2034  # paths are consumed by the sibling libs, not this file
# render.sh — derived markdown.
#
# The log and the parking lot are append-shaped: humans add lines, and every
# append is already a journal event. The markdown itself is therefore a render
# of the views, regenerated in .local/render/ on every views_rebuild — which
# keeps it out of the synced tree, so generated content can never conflict.
#
# Byte-format is the one cmd_log / cmd_park always produced, because the
# parsers in review.sh, focus.sh, the session-start hook and the dashboard
# read these files. The only addition is a first-line HTML comment naming the
# file as generated; every parser skips comment lines.
#
# Sourced by dave.sh.

GENERATED_NOTE='<!-- generated by dave.sh from the journal; edit with: dave.sh log / dave.sh park -->'

render_views() {
  mkdir -p "$RENDER/log"
  _render_logs || return 1
  _render_parking
}

# One <date>.md per day the log view knows about; files for days that no
# longer appear are removed (only inside $RENDER/log — nothing else lives
# there).
_render_logs() {
  local dates d f tmp
  dates="$(jq -r 'keys[]' "$VIEWS/log.json" 2>/dev/null || true)"
  for f in "$RENDER/log"/*.md; do
    [ -e "$f" ] || continue
    d="$(basename "$f" .md)"
    case " $dates " in *" $d "*) ;; *) rm -f "$f" ;; esac
  done
  for d in $dates; do
    f="$RENDER/log/$d.md"
    tmp="$(mktemp "$f.XXXXXX")"
    {
      printf '%s\n' "$GENERATED_NOTE"
      printf '# %s\n\n' "$(date -d "$d" '+%A, %B %-d, %Y' 2>/dev/null || echo "$d")"
      jq -r --arg d "$d" '
        .[$d][] | "- `\(.time)` "
          + (if (.ref // "") != "" then "**\(.ref)** — " else "" end)
          + .text' "$VIEWS/log.json"
    } > "$tmp" && mv "$tmp" "$f" || return 1
  done
}

# Header block identical to what cmd_init wrote, then open items as `- [ ]`
# and retired as `- [x]`, oldest first. The retired suffix matches the one
# _parked_done appended: ` _(retired YYYY-MM-DD)_`.
_render_parking() {
  local tmp
  tmp="$(mktemp "$PARKING.XXXXXX")"
  {
    printf '%s\n' "$GENERATED_NOTE"
    printf '# Parking Lot\n\nCaptured detours, deferred ideas, and anything that pulled focus off the list.\nOpen items are `- [ ]`; retired ones `- [x]`.\n\n'
    jq -r '.[] |
      (if .done == null then "- [ ]" else "- [x]" end) + " " + .text
      + " _(parked \(.parked_at)"
      + (if (.ref // "") != "" then ", while on \(.ref)" else "" end) + ")_"
      + (if .done == null then "" else " _(retired \(.done))_" end)' \
      "$VIEWS/parked.json"
  } > "$tmp" && mv "$tmp" "$PARKING"
}
